server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-client
  cloud:
    config:
      discovery:
        service-id: config-server
      #配置中心服务器地址配置
      uri: http://127.0.0.1:8765/
      profile: dev
      label: master
      retry:
        # 配置重试次数，默认为6
        max-attempts: 6
        # 间隔乘数 默认1.1
        multiplier: 1.1
        # 初始重试间隔时间，默认1000ms
        initial-interval: 1000
        # 最大间隔时间，默认2000ms
        max-interval: 2000