server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server #git仓库中该项目的默认配置文件 config-server.yml
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangYongQiang0805/springcloud-config-git
